on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: egonbraun/terraform-lint-action@v1.0.0
    - name: Test
      uses: egonbraun/terraform-test-action@v1.0.0
